FROM 67df80803f73

ARG NODE
ENV NODE_ENV ${NODE}

RUN useradd --user-group --create-home --shell /bin/false dandelion && echo
ENV HOME=/home/dandelion
WORKDIR $HOME/client
ENV NODE_PATH /client-deps/node_modules

EXPOSE 3000
USER dandelion
CMD ["./scripts/start.sh"]
