FROM dandelion_server-schema

ARG NODE
ENV NODE_ENV ${NODE}

WORKDIR $HOME/client
ENV NODE_PATH $HOME/client/node_modules

ADD . .
RUN NODE_ENV=development npm install && node ./scripts/build.js
# && rm -r node_modules src # this leaves out pushstate-server :-/

EXPOSE 3000
USER dandelion
CMD ["./node_modules/pushstate-server/bin/pushstate-server", "build", "3000"]
