FROM nodesource/node:6.3.0

RUN useradd --user-group --create-home --shell /bin/false dandelion && echo
ENV HOME=/home/dandelion
WORKDIR $HOME/server
ENV NODE_PATH $HOME/server/node_modules

ADD . .
RUN NODE_ENV=development npm install

RUN ./scripts/build-update-schema.sh
