FROM dandeliondev_server-deps

RUN useradd --user-group --create-home --shell /bin/false dandelion && echo
ENV HOME=/home/dandelion
WORKDIR $HOME/server
ENV NODE_PATH /server-deps/node_modules

USER dandelion
CMD ["./scripts/update-schema.sh"]
