FROM dandeliondev_server-deps

ARG NODE
ENV NODE_ENV ${NODE}

RUN useradd --user-group --create-home --shell /bin/false dandelion && echo
ENV HOME=/home/dandelion
WORKDIR $HOME/server
ENV NODE_PATH /server-deps/node_modules

EXPOSE 8080
USER dandelion
CMD ["./scripts/start.sh"]
