version: '2'
services:
    schema:
        build:
            context: ../app
            dockerfile: ./config/Dockerfile.schema.prod
    app:
        build:
            context: ../app
            dockerfile: ./config/Dockerfile.prod
            args:
                - NODE=production
        depends_on:
            - schema
