version: '2'
services:
    db:
        image: postgres
        ports:
            - "3002:5432"
    deps:
        build:
            context: ../app
            dockerfile: ./config/Dockerfile.deps.dev
        volumes:
            - dandelion:/home/dandelion
    schema:
        build:
            context: ../app
            dockerfile: ./config/Dockerfile.schema.dev
        depends_on:
            - deps
        volumes:
            - dandelion:/home/dandelion
            - ../app:/home/dandelion/app
    app:
        build:
            context: ../app
            dockerfile: ./config/Dockerfile.dev
            args:
                - NODE=development
        ports:
            - "3000:3000"
            - "3001:8080"
        links:
            - db
        depends_on:
            - db
            - deps
            - schema
        volumes:
            - dandelion:/home/dandelion
            - ../app:/home/dandelion/app
        environment:
            - PGHOST=db
            - PGDATABASE=postgres
            - PGUSER=postgres
volumes:
    dandelion: {}
