version: '2'
services:
    db:
        image: postgres
        ports:
            - "3002:5432"
    app:
        image: sheepie/dandelion-app
        ports:
            - "3000:3000"
        links:
            - db
        environment:
            - PGHOST=db
            - PGDATABASE=postgres
            - PGUSER=postgres
