version: '2'
services:
    server-schema:
        build:
            context: ../server
            dockerfile: ./config/Dockerfile.schema.prod
    server:
        build:
            context: ../server
            dockerfile: ./config/Dockerfile.prod
            args:
                - NODE=production
        depends_on:
            - server-schema
    client:
        build:
            context: ../client
            dockerfile: ./config/Dockerfile.prod
            args:
                - NODE=production
        depends_on:
            - server-schema
