version: '2'
services:
    db:
        image: postgres
        ports:
            - "3002:5432"
        volumes:
            - /srv/db/dandelion-postgres:/var/lib/postgresql/data
    app:
        image: sheepie/dandelion-app
        ports:
            - "3000:3000"
            - "3001:8080"
        links:
            - db
        environment:
            - PGHOST=db
            - PGDATABASE=postgres
            - PGUSER=postgres
